twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true

easy_admin:
    entities:
        Inscrit:
            class: App\Entity\Inscrit
            form:
                fields:
                    - { property: 'Competences', type: 'easyadmin_autocomplete', multiple: true, class: App\Entity\TypeCompetences, choice_label: 'intitule' }
