controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

accueil:
    path: /
    controller: App\Controller\AccueilController::index


    # Materiel

materielConsulter:
    path: /materiel/consulter/{id}
    controller: App\Controller\MaterielController::consulterMateriel

materielLister:
    path: /materiel/lister/
    controller: App\Controller\MaterielController::listerMateriel

materielAjouter:
    path: /materiel/ajouter/
    controller: App\Controller\MaterielController::ajouterMateriel

materielModifier:
    path: /materiel/modifier/{id}
    controller: App\Controller\MaterielController::modifierMateriel

materielSupprimer:
    path: /materiel/supprimer/{id}
    controller: App\Controller\MaterielController::supprimerMateriel

#Connexion/Inscription

inscription:
    path: /inscription
    controller: App\Controller\RegistrationController::register

connexion:
    path: /connexion
    controller: App\Controller\LoginController::index

logout:
    path: /logout
    methods: GET

#Inscrit

consulterInscrit:
    path: /inscrit/consulter/{id}
    controller: App\Controller\InscritController::consulterInscrit

modifierInscrit:
    path: /inscrit/modifier/{id}
    controller: App\Controller\InscritController::modifierInscrit