controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

accueil:
    path: /accueil
    controller: App\Controller\AccueilController::index


    # Materiel

materielConsulter:
    path: /materiel/consulter/{id}
    controller: App\Controller\MaterielController::consulterMateriel

materielLister:
    path: /materiel/lister/
    controller: App\Controller\MaterielController::listerMateriel

#Connexion/Inscription

inscription:
    path: /inscription
    controller: App\Controller\RegistrationController::register

connexion:
    path: /connexion
    controller: App\Controller\LoginController::index