controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

accueil:
    path: /
    controller: App\Controller\AccueilController::index


    # Materiel

materielConsulter:
    path: /materiel/consulter/{id}
    controller: App\Controller\MaterielController::consulterMateriel

materielLister:
    path: /materiel/lister/
    controller: App\Controller\MaterielController::listerMateriel

materielAjouter:
    path: /materiel/ajouter/
    controller: App\Controller\MaterielController::ajouterMateriel

materielModifier:
    path: /materiel/modifier/{id}
    controller: App\Controller\MaterielController::modifierMateriel

materielSupprimer:
    path: /materiel/supprimer/{id}
    controller: App\Controller\MaterielController::supprimerMateriel


#Connexion/Inscription

inscription:
    path: /inscription
    controller: App\Controller\RegistrationController::register

connexion:
    path: /connexion
    controller: App\Controller\LoginController::index

logout:
    path: /logout
    methods: GET


   # Emprunt

empruntConsulter:
    path: /emprunt/consulter/{id}
    controller: App\Controller\EmpruntController::consulterEmprunt

empruntLister:
    path: /emprunt/lister/
    controller: App\Controller\EmpruntController::listerEmprunt

empruntAjouter:
    path: /emprunt/ajouter/{id}
    controller: App\Controller\EmpruntController::ajouterEmprunt

empruntModifier:
    path: /emprunt/modifier/{id}
    controller: App\Controller\EmpruntController::modifierEmprunt

empruntSupprimer:
    path: /emprunt/supprimer/{id}
    controller: App\Controller\EmpruntController::supprimerEmprunt

adminEmprunt:
    path: /emprunt/ajouter/
    controller: App\Controller\EmpruntController::adminEmprunt

empruntConsulterPerso:
    path: /emprunt/consulterPerso/{id}
    controller: App\Controller\EmpruntController::consulterEmpruntsPerso


#Inscrit

consulterInscrit:
    path: /inscrit/consulter/{id}
    controller: App\Controller\InscritController::consulterInscrit

modifierInscrit:
    path: /inscrit/modifier/{id}
    controller: App\Controller\InscritController::modifierInscrit

supprimerInscrit:
    path: /inscrit/supprimer/{id}
    controller: App\Controller\InscritController::supprimerInscrit

listerInscrit:
    path: /inscrit/lister/
    controller: App\Controller\InscritController::listerInscrit

trombiInscrit:
    path: /inscrit/trombi/
    controller: App\Controller\InscritController::trombiInscrit

telechargerInscritPdf:
    path: /inscrit/pdf/{id}
    controller: App\Controller\InscritController::telechargerInscritPdf  

telechargerTrombiPdf:
    path: /inscrit/trombi/pdf
    controller: App\Controller\InscritController::telechargerTrombiPdf  